# Generated by Django 5.1.6 on 2025-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
    ]
