# Generated by Django 5.1.6 on 2025-02-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('portrait', 'portrait'), ('paysage', 'paysage')], max_length=10)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
