# Generated by Django 5.1.6 on 2025-02-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_delete_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
