# Generated by Django 5.1.6 on 2025-02-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_rename_type_photo_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='subPage',
            field=models.CharField(blank=True, choices=[('portrait', 'portrait'), ('artisan', 'artisan'), ('boudoir', 'boudoir'), ('collaborationArtistique', 'collaborationArtistique'), ('fantastique', 'fantastique'), ('lumiereNaturelle', 'lumiereNaturelle'), ('nu', 'nu'), ('studio', 'studio'), ('apropos', 'apropos')], max_length=50, null=True),
        ),
    ]
