# Generated by Django 5.1.6 on 2025-02-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_subpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='subPage',
            new_name='context',
        ),
    ]
