# Generated by Django 5.1.6 on 2025-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_rename_subpage_photo_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='context',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='role',
        ),
        migrations.AddField(
            model_name='photo',
            name='subject',
            field=models.CharField(choices=[('po_collaborationArtistique', 'po_collaborationArtistique'), ('po_fantastique', 'po_fantastique'), ('po_lumiereNaturelle', 'po_lumiereNaturelle'), ('po_nuLingerie', 'po_nuLingerie'), ('po_studio', 'po_studio'), ('pre_portrait', 'pre_portrait'), ('pre_artisan', 'pre_artisan'), ('pre_boudoir', 'pre_boudoir'), ('ar_byLou', 'ar_byLou')], default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('prestation', 'prestation'), ('portefolio', 'portefolio'), ('artisan', 'artisan')], default='po_fantastique', max_length=50),
            preserve_default=False,
        ),
    ]
