# Generated by Django 5.1.6 on 2025-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
