# Generated by Django 5.1.6 on 2025-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_alter_photo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('galery', 'galery'), ('banner', 'banner'), ('representant', 'representant')], max_length=50, null=True),
        ),
    ]
