# Generated by Django 5.1.6 on 2025-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_alter_photo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('representant', 'representant'), ('galery', 'galery'), ('banner', 'banner')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Atelier by Lou', 'Atelier by Lou'), ('Autre', 'Autre')], max_length=50)),
                ('photos', models.ManyToManyField(blank=True, related_name='artisans', to='photos.photo')),
            ],
        ),
    ]
