# Generated by Django 5.1.6 on 2025-02-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0041_alter_photo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('representant', 'representant'), ('galery', 'galery'), ('banner', 'banner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='subject',
            field=models.CharField(choices=[('po_collaborationArtistique', 'po_collaborationArtistique'), ('po_fantastique', 'po_fantastique'), ('po_lumiereNaturelle', 'po_lumiereNaturelle'), ('po_nuLingerie', 'po_nuLingerie'), ('po_studio', 'po_studio'), ('pre_portrait', 'pre_portrait'), ('pre_artisan', 'pre_artisan'), ('pre_boudoir', 'pre_boudoir')], max_length=50),
        ),
    ]
