# Generated by Django 5.1.6 on 2025-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0042_alter_photo_role_alter_photo_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('representant', 'representant'), ('banner', 'banner'), ('galery', 'galery')], max_length=50, null=True),
        ),
    ]
