# Generated by Django 5.1.6 on 2025-03-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0043_alter_photo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='name',
            field=models.CharField(choices=[('Atelier by Lau', 'Atelier by Lau'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('banner', 'banner'), ('representant', 'representant'), ('galery', 'galery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='subject',
            field=models.CharField(choices=[('po_collaborationArtistique', 'po_collaborationArtistique'), ('po_fantastique', 'po_fantastique'), ('po_lumiereNaturelle', 'po_lumiereNaturelle'), ('po_nuLingerie', 'po_nuLingerie'), ('po_studio', 'po_studio'), ('po_retoucheCreatives', 'po_retoucheCreatives'), ('pre_portrait', 'pre_portrait'), ('pre_artisan', 'pre_artisan'), ('pre_boudoir', 'pre_boudoir')], max_length=50),
        ),
    ]
