# Generated by Django 5.2 on 2025-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0044_alter_artisan_name_alter_photo_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('representant', 'representant'), ('banner', 'banner'), ('galery', 'galery')], max_length=50, null=True),
        ),
    ]
