# Generated by Django 5.2 on 2025-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0045_alter_photo_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='type',
        ),
        migrations.AlterField(
            model_name='artisan',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Photos lié à cet artisan', related_name='artisans', to='photos.photo'),
        ),
        migrations.CreateModel(
            name='Portefolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photos', models.ManyToManyField(blank=True, help_text='Photos incluses dans ce portefolio', related_name='portefolios', to='photos.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('delivery', models.IntegerField()),
                ('photos', models.ManyToManyField(blank=True, help_text='Photos incluses dans cette prestation', related_name='prestations', to='photos.photo')),
            ],
        ),
    ]
