# Generated by Django 5.2 on 2025-05-08 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0046_remove_photo_subject_remove_photo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('galery', 'galery'), ('banner', 'banner'), ('representant', 'representant')], max_length=50, null=True),
        ),
    ]
