# Generated by Django 5.2 on 2025-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0047_prestation_created_at_alter_photo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('representant', 'representant'), ('banner', 'banner'), ('galery', 'galery')], max_length=50, null=True),
        ),
    ]
