# Generated by Django 5.2 on 2025-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0048_prestation_description_alter_photo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='role',
            field=models.CharField(blank=True, choices=[('galery', 'galery'), ('representant', 'representant'), ('banner', 'banner')], max_length=50, null=True),
        ),
    ]
