# Generated by Django 5.2 on 2025-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0049_alter_artisan_name_alter_photo_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='role',
        ),
        migrations.AddField(
            model_name='photo',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='representant',
            field=models.BooleanField(default=False),
        ),
    ]
